export const ALL_ACTIVE_GAMES_REQUESTED = 'FETCH_GAMES_REQUESTED';
export const ALL_ACTIVE_GAMES_UPDATED = 'ALL_ACTIVE_GAMES_UPDATED';

export const GAME_SELECT = 'GAME_SELECT';

export const FETCH_YELP_BUSINESSES_REQUESTED =
    'FETCH_YELP_BUSINESSES_REQUESTED';
export const FETCH_YELP_BUSINESSES_SUCCESS = 'FETCH_YELP_BUSINESSES_SUCCESS';
export const FETCH_YELP_BUSINESSES_FAILURE = 'FETCH_YELP_BUSINESSES_FAILURE';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';

export const TOKEN_LOGIN_REQUESTED = 'TOKEN_LOGIN_REQUESTED';
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS';
export const TOKEN_LOGIN_FAILURE = 'TOKEN_LOGIN_FAILURE';

export const CHAT_USERS_ONLINE_UPDATE = 'CHAT_USERS_ONLINE_UPDATE';
export const CHAT_SELECT = 'CHAT_SELECT';
export const CHAT_ADD = 'CHAT_ADD';
export const MESSAGES_LOAD = 'MESSAGES_LOAD';
export const MESSAGE_ADD = 'MESSAGE_ADD';
export const CHAT_PROFILE_LOAD = 'CHAT_PROFILE_LOAD';
export const TYPING_UPDATE = 'TYPING_UPDATE';

export const GAME_MESSAGES_LOAD = 'GAME_MESSAGES_LOAD';
export const GAME_MESSAGE_ADD = 'GAME_MESSAGE_ADD';
export const GAME_TYPING_UPDATE = 'GAME_TYPING_UPDATE';

export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const USER_HISTORY_LOAD = 'USER_HISTORY_LOAD';
